---
- hosts: all
  user: "{{ os_user }}" 
  become: yes
  gather_facts: yes
  # pre_tasks:
  #  - name: Wait for automatic system updates
  #    shell: while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;
  #  - name: Seed ansible on remote instances (no python errors)
  #    raw: sudo apt-get -y install python-simplejson aptitude
  #  - action: setup
  
  roles:
    - common
    - databundle
